apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    db: mysql
    type: demo
  name: mysql-db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      db: mysql
      type: demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        db: mysql
        type: demo
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: demo
        image: mysql:8.0.18
        name: mysql-db
        resources:
          limits:
            cpu: "1600m"
            memory: 6000Mi
          requests:
            cpu: "1500m"
            memory: 5000Mi
status: {}
